In [1]:
import numpy as np
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [2]:
array = np.linspace(-3,3,num=100)
array * 10

array([-30.        , -29.39393939, -28.78787879, -28.18181818,
       -27.57575758, -26.96969697, -26.36363636, -25.75757576,
       -25.15151515, -24.54545455, -23.93939394, -23.33333333,
       -22.72727273, -22.12121212, -21.51515152, -20.90909091,
       -20.3030303 , -19.6969697 , -19.09090909, -18.48484848,
       -17.87878788, -17.27272727, -16.66666667, -16.06060606,
       -15.45454545, -14.84848485, -14.24242424, -13.63636364,
       -13.03030303, -12.42424242, -11.81818182, -11.21212121,
       -10.60606061, -10.        ,  -9.39393939,  -8.78787879,
        -8.18181818,  -7.57575758,  -6.96969697,  -6.36363636,
        -5.75757576,  -5.15151515,  -4.54545455,  -3.93939394,
        -3.33333333,  -2.72727273,  -2.12121212,  -1.51515152,
        -0.90909091,  -0.3030303 ,   0.3030303 ,   0.90909091,
         1.51515152,   2.12121212,   2.72727273,   3.33333333,
         3.93939394,   4.54545455,   5.15151515,   5.75757576,
         6.36363636,   6.96969697,   7.57575758,   8.18181818,
         8.78787879,   9.39393939,  10.        ,  10.60606061,
        11.21212121,  11.81818182,  12.42424242,  13.03030303,
        13.63636364,  14.24242424,  14.84848485,  15.45454545,
        16.06060606,  16.66666667,  17.27272727,  17.87878788,
        18.48484848,  19.09090909,  19.6969697 ,  20.3030303 ,
        20.90909091,  21.51515152,  22.12121212,  22.72727273,
        23.33333333,  23.93939394,  24.54545455,  25.15151515,
        25.75757576,  26.36363636,  26.96969697,  27.57575758,
        28.18181818,  28.78787879,  29.39393939,  30.        ])

In [3]:
np.random.randint(50,size=100,high=101)

array([ 99,  56,  86,  82,  84,  80,  96,  52,  84,  67,  99,  81,  59,
        72,  77,  53,  83,  55,  92,  70,  74,  78,  99,  83,  63,  87,
        50,  70,  64,  97,  91,  93,  83,  76,  51,  85,  68,  75,  62,
        67,  78,  55,  78,  74,  52,  66,  57,  96,  58,  59,  93,  81,
        87,  63,  70,  66,  85,  65,  64,  67,  82,  91,  99,  64,  53,
        78,  96,  59,  62,  75,  67,  54,  65, 100,  78,  72,  77,  53,
        90, 100,  53,  72,  67,  78,  57,  95,  88,  71,  71,  51,  86,
        83,  58,  99,  81,  99,  77,  52,  78,  70])

In [4]:
np.random.randint(50,size=(50,5),high=101)

array([[ 62,  88,  59,  77,  92],
       [ 55,  84,  52,  74,  75],
       [ 64,  82,  85,  50,  58],
       [ 68,  70,  62,  79,  95],
       [ 65,  60,  77,  80,  84],
       [ 77,  75,  71,  50,  50],
       [ 61,  57,  63,  86,  53],
       [ 54,  80,  58,  53,  60],
       [ 96,  65,  94,  90,  94],
       [ 55,  82,  77,  82,  54],
       [ 96,  69,  81,  51,  94],
       [ 78,  81,  84,  58,  59],
       [ 79,  54,  58,  97,  59],
       [100,  92,  84,  86,  73],
       [ 78,  54,  76,  75,  64],
       [ 96,  96,  54,  52,  82],
       [ 58,  65,  60,  64,  97],
       [ 63,  68,  86,  90,  84],
       [ 80,  88,  89,  58,  64],
       [ 60,  60,  66,  65,  92],
       [ 70,  80,  89,  96,  71],
       [ 73,  85,  66,  69,  81],
       [ 96,  78,  65,  54,  54],
       [ 70,  90,  52,  80, 100],
       [ 70,  80,  78,  98,  50],
       [ 90,  61,  89,  65,  93],
       [ 80,  83,  62,  73,  84],
       [ 95,  77,  82,  66,  95],
       [ 57,  93,  97,  54,  71],
       [ 62,  74,  59,  94,  80],
       [ 96,  93,  62,  87,  87],
       [ 60,  56,  83,  57,  89],
       [ 69,  99,  52,  62,  85],
       [ 77,  84,  65,  66,  59],
       [ 53,  65,  55,  93,  72],
       [ 61,  99,  85,  54,  77],
       [ 73,  99,  71,  90,  50],
       [ 99,  56,  76,  79,  64],
       [ 71,  89,  89,  78,  83],
       [ 68,  53,  88,  72,  85],
       [ 73,  84,  97,  55,  73],
       [ 73,  84,  56,  84,  60],
       [ 99,  77,  66,  60,  83],
       [ 93,  71,  72,  59,  87],
       [ 64,  70,  68,  78,  82],
       [ 90,  74,  63,  91,  62],
       [ 94,  96,  90,  90,  85],
       [ 79,  78,  79,  51,  80],
       [ 81,  81,  60,  90,  62],
       [ 65,  57,  83,  83,  51]])

In [6]:
content = np.random.randint(50,size=(50,5),high=101)
import pandas as pd
df1 = pd.DataFrame(data=content,
             index=range(1,51),
             columns=['國文','英文','數學','地理','歷史'])
df1

     國文  英文   數學   地理   歷史
1    72  99   83   83   75
2    62  82   74   89   83
3    63  53   77   89   58
4    59  95   66   87   79
5    77  98   57   86   92
6    96  86   54   89   88
7    53  71   70  100   99
8    64  64   66   85   91
9    84  65   59   60   61
10   57  55   59   91   96
11   50  62   68   89  100
12   90  70   96   59   53
13   62  56   77   55   52
14   76  98   61   79   71
15   67  60   56   81   50
16   64  51   71   86   82
17   94  59   87   89  100
18   61  73   87   60   90
19   76  90   85   78   76
20   71  63   91   59   50
21   72  73   57   52   63
22   67  69   50   94   76
23   69  64   77   73   68
24   65  68   70   74   93
25   54  90  100   69   86
26   59  58   77   59   84
27   79  86   53   60   99
28   61  64   91   55   58
29   99  99   81   74   51
30  100  89   74   93   73
31   77  69   99   55   91
32   86  71   65  100   80
33   52  96   68   76   90
34   93  52   63   65   79
35   66  51   97   53   50
36   95  55   87   73   52
37   99  89   63   58   80
38   61  82   66   62   57
39   73  72   81   78   69
40   66  84   81   95   73
41   59  92   66   75   70
42   69  74   84   85   57
43   82  51   84   68   91
44   69  98   66   52   95
45   61  92   83   98   96
46   67  92   71   91   64
47   72  93   90   79   51
48   93  73   70   68   95
49   80  62   96   60   60
50   97  51   83   55   96

In [7]:
df1['國文'] + df1['英文'] + df1['數學'] + df1['地理'] + df1['歷史']

1     412
2     390
3     340
4     386
5     410
6     413
7     393
8     370
9     329
10    358
11    369
12    368
13    302
14    385
15    314
16    354
17    429
18    371
19    405
20    334
21    317
22    356
23    351
24    370
25    399
26    337
27    377
28    329
29    404
30    429
31    391
32    402
33    382
34    352
35    317
36    362
37    389
38    328
39    373
40    399
41    362
42    369
43    376
44    380
45    430
46    385
47    385
48    399
49    358
50    382
dtype: int64

In [8]:
df1.to_excel('score.xlsx',sheet_name='2024_06_27')

In [10]:
import pandas as pd
df1 = pd.DataFrame(data=content,
             index=[f"第{i}號"for i in range(1,51)],
             columns=['國文','英文','數學','地理','歷史'])
df1

       國文  英文   數學   地理   歷史
第1號    72  99   83   83   75
第2號    62  82   74   89   83
第3號    63  53   77   89   58
第4號    59  95   66   87   79
第5號    77  98   57   86   92
第6號    96  86   54   89   88
第7號    53  71   70  100   99
第8號    64  64   66   85   91
第9號    84  65   59   60   61
第10號   57  55   59   91   96
第11號   50  62   68   89  100
第12號   90  70   96   59   53
第13號   62  56   77   55   52
第14號   76  98   61   79   71
第15號   67  60   56   81   50
第16號   64  51   71   86   82
第17號   94  59   87   89  100
第18號   61  73   87   60   90
第19號   76  90   85   78   76
第20號   71  63   91   59   50
第21號   72  73   57   52   63
第22號   67  69   50   94   76
第23號   69  64   77   73   68
第24號   65  68   70   74   93
第25號   54  90  100   69   86
第26號   59  58   77   59   84
第27號   79  86   53   60   99
第28號   61  64   91   55   58
第29號   99  99   81   74   51
第30號  100  89   74   93   73
第31號   77  69   99   55   91
第32號   86  71   65  100   80
第33號   52  96   68   76   90
第34號   93  52   63   65   79
第35號   66  51   97   53   50
第36號   95  55   87   73   52
第37號   99  89   63   58   80
第38號   61  82   66   62   57
第39號   73  72   81   78   69
第40號   66  84   81   95   73
第41號   59  92   66   75   70
第42號   69  74   84   85   57
第43號   82  51   84   68   91
第44號   69  98   66   52   95
第45號   61  92   83   98   96
第46號   67  92   71   91   64
第47號   72  93   90   79   51
第48號   93  73   70   68   95
第49號   80  62   96   60   60
第50號   97  51   83   55   96

In [11]:
df1.loc["第1號",:]

國文    72
英文    99
數學    83
地理    83
歷史    75
Name: 第1號, dtype: int64

In [12]:
df1.loc[["第1號","第5號","第10號"]]

      國文  英文  數學  地理  歷史
第1號   72  99  83  83  75
第5號   77  98  57  86  92
第10號  57  55  59  91  96

In [13]:
df1.iloc[:5]

     國文  英文  數學  地理  歷史
第1號  72  99  83  83  75
第2號  62  82  74  89  83
第3號  63  53  77  89  58
第4號  59  95  66  87  79
第5號  77  98  57  86  92

In [15]:
df1.iloc[-5:]

      國文  英文  數學  地理  歷史
第46號  67  92  71  91  64
第47號  72  93  90  79  51
第48號  93  73  70  68  95
第49號  80  62  96  60  60
第50號  97  51  83  55  96

In [16]:
df1.loc['第10號':'第15號']

      國文  英文  數學  地理   歷史
第10號  57  55  59  91   96
第11號  50  62  68  89  100
第12號  90  70  96  59   53
第13號  62  56  77  55   52
第14號  76  98  61  79   71
第15號  67  60  56  81   50

In [17]:
student_sum = df1.sum(axis=1)
student_mean = df1.mean(axis=1)
df1['總分'] = student_sum
df1['平均'] = student_mean
df1

       國文  英文   數學   地理   歷史   總分    平均
第1號    72  99   83   83   75  412  82.4
第2號    62  82   74   89   83  390  78.0
第3號    63  53   77   89   58  340  68.0
第4號    59  95   66   87   79  386  77.2
第5號    77  98   57   86   92  410  82.0
第6號    96  86   54   89   88  413  82.6
第7號    53  71   70  100   99  393  78.6
第8號    64  64   66   85   91  370  74.0
第9號    84  65   59   60   61  329  65.8
第10號   57  55   59   91   96  358  71.6
第11號   50  62   68   89  100  369  73.8
第12號   90  70   96   59   53  368  73.6
第13號   62  56   77   55   52  302  60.4
第14號   76  98   61   79   71  385  77.0
第15號   67  60   56   81   50  314  62.8
第16號   64  51   71   86   82  354  70.8
第17號   94  59   87   89  100  429  85.8
第18號   61  73   87   60   90  371  74.2
第19號   76  90   85   78   76  405  81.0
第20號   71  63   91   59   50  334  66.8
第21號   72  73   57   52   63  317  63.4
第22號   67  69   50   94   76  356  71.2
第23號   69  64   77   73   68  351  70.2
第24號   65  68   70   74   93  370  74.0
第25號   54  90  100   69   86  399  79.8
第26號   59  58   77   59   84  337  67.4
第27號   79  86   53   60   99  377  75.4
第28號   61  64   91   55   58  329  65.8
第29號   99  99   81   74   51  404  80.8
第30號  100  89   74   93   73  429  85.8
第31號   77  69   99   55   91  391  78.2
第32號   86  71   65  100   80  402  80.4
第33號   52  96   68   76   90  382  76.4
第34號   93  52   63   65   79  352  70.4
第35號   66  51   97   53   50  317  63.4
第36號   95  55   87   73   52  362  72.4
第37號   99  89   63   58   80  389  77.8
第38號   61  82   66   62   57  328  65.6
第39號   73  72   81   78   69  373  74.6
第40號   66  84   81   95   73  399  79.8
第41號   59  92   66   75   70  362  72.4
第42號   69  74   84   85   57  369  73.8
第43號   82  51   84   68   91  376  75.2
第44號   69  98   66   52   95  380  76.0
第45號   61  92   83   98   96  430  86.0
第46號   67  92   71   91   64  385  77.0
第47號   72  93   90   79   51  385  77.0
第48號   93  73   70   68   95  399  79.8
第49號   80  62   96   60   60  358  71.6
第50號   97  51   83   55   96  382  76.4

In [18]:
df2 = df1.sort_values(by='總分',ascending=False)

In [19]:
df2.iloc[:5]

       國文  英文  數學  地理   歷史   總分    平均
第45號   61  92  83  98   96  430  86.0
第17號   94  59  87  89  100  429  85.8
第30號  100  89  74  93   73  429  85.8
第6號    96  86  54  89   88  413  82.6
第1號    72  99  83  83   75  412  82.4

In [20]:
df2.iloc[-5:]

      國文  英文  數學  地理  歷史   總分    平均
第38號  61  82  66  62  57  328  65.6
第21號  72  73  57  52  63  317  63.4
第35號  66  51  97  53  50  317  63.4
第15號  67  60  56  81  50  314  62.8
第13號  62  56  77  55  52  302  60.4

In [21]:
df2['排名'] = df1['總分'].rank(method='first',ascending=False)

In [22]:
df2

       國文  英文   數學   地理   歷史   總分    平均    排名
第45號   61  92   83   98   96  430  86.0   1.0
第17號   94  59   87   89  100  429  85.8   2.0
第30號  100  89   74   93   73  429  85.8   3.0
第6號    96  86   54   89   88  413  82.6   4.0
第1號    72  99   83   83   75  412  82.4   5.0
第5號    77  98   57   86   92  410  82.0   6.0
第19號   76  90   85   78   76  405  81.0   7.0
第29號   99  99   81   74   51  404  80.8   8.0
第32號   86  71   65  100   80  402  80.4   9.0
第25號   54  90  100   69   86  399  79.8  10.0
第48號   93  73   70   68   95  399  79.8  12.0
第40號   66  84   81   95   73  399  79.8  11.0
第7號    53  71   70  100   99  393  78.6  13.0
第31號   77  69   99   55   91  391  78.2  14.0
第2號    62  82   74   89   83  390  78.0  15.0
第37號   99  89   63   58   80  389  77.8  16.0
第4號    59  95   66   87   79  386  77.2  17.0
第14號   76  98   61   79   71  385  77.0  18.0
第47號   72  93   90   79   51  385  77.0  20.0
第46號   67  92   71   91   64  385  77.0  19.0
第33號   52  96   68   76   90  382  76.4  21.0
第50號   97  51   83   55   96  382  76.4  22.0
第44號   69  98   66   52   95  380  76.0  23.0
第27號   79  86   53   60   99  377  75.4  24.0
第43號   82  51   84   68   91  376  75.2  25.0
第39號   73  72   81   78   69  373  74.6  26.0
第18號   61  73   87   60   90  371  74.2  27.0
第8號    64  64   66   85   91  370  74.0  28.0
第24號   65  68   70   74   93  370  74.0  29.0
第42號   69  74   84   85   57  369  73.8  31.0
第11號   50  62   68   89  100  369  73.8  30.0
第12號   90  70   96   59   53  368  73.6  32.0
第41號   59  92   66   75   70  362  72.4  34.0
第36號   95  55   87   73   52  362  72.4  33.0
第49號   80  62   96   60   60  358  71.6  36.0
第10號   57  55   59   91   96  358  71.6  35.0
第22號   67  69   50   94   76  356  71.2  37.0
第16號   64  51   71   86   82  354  70.8  38.0
第34號   93  52   63   65   79  352  70.4  39.0
第23號   69  64   77   73   68  351  70.2  40.0
第3號    63  53   77   89   58  340  68.0  41.0
第26號   59  58   77   59   84  337  67.4  42.0
第20號   71  63   91   59   50  334  66.8  43.0
第28號   61  64   91   55   58  329  65.8  45.0
第9號    84  65   59   60   61  329  65.8  44.0
第38號   61  82   66   62   57  328  65.6  46.0
第21號   72  73   57   52   63  317  63.4  47.0
第35號   66  51   97   53   50  317  63.4  48.0
第15號   67  60   56   81   50  314  62.8  49.0
第13號   62  56   77   55   52  302  60.4  50.0